// Code generated by the generate_ast tool; DO NOT EDIT.
package glox

type Expr interface {
	Accept(v visitor) interface{}
	AcceptBool(v visitorBool) bool
	AcceptString(v visitorString) string
	AcceptInt(v visitorInt) int
	AcceptInt8(v visitorInt8) int8
	AcceptInt16(v visitorInt16) int16
	AcceptInt32(v visitorInt32) int32
	AcceptInt64(v visitorInt64) int64
	AcceptUint(v visitorUint) uint
	AcceptUint8(v visitorUint8) uint8
	AcceptUint16(v visitorUint16) uint16
	AcceptUint32(v visitorUint32) uint32
	AcceptUint64(v visitorUint64) uint64
	AcceptUintptr(v visitorUintptr) uintptr
	AcceptByte(v visitorByte) byte
	AcceptRune(v visitorRune) rune
	AcceptFloat32(v visitorFloat32) float32
	AcceptFloat64(v visitorFloat64) float64
	AcceptComplex64(v visitorComplex64) complex64
	AcceptComplex128(v visitorComplex128) complex128
}

type visitor interface {
	visitBinaryExpr(*Binary) interface{}
	visitGroupingExpr(*Grouping) interface{}
	visitLiteralExpr(*Literal) interface{}
	visitUnaryExpr(*Unary) interface{}
}

type visitorBool interface {
	visitBinaryExpr(*Binary) bool
	visitGroupingExpr(*Grouping) bool
	visitLiteralExpr(*Literal) bool
	visitUnaryExpr(*Unary) bool
}

type visitorString interface {
	visitBinaryExpr(*Binary) string
	visitGroupingExpr(*Grouping) string
	visitLiteralExpr(*Literal) string
	visitUnaryExpr(*Unary) string
}

type visitorInt interface {
	visitBinaryExpr(*Binary) int
	visitGroupingExpr(*Grouping) int
	visitLiteralExpr(*Literal) int
	visitUnaryExpr(*Unary) int
}

type visitorInt8 interface {
	visitBinaryExpr(*Binary) int8
	visitGroupingExpr(*Grouping) int8
	visitLiteralExpr(*Literal) int8
	visitUnaryExpr(*Unary) int8
}

type visitorInt16 interface {
	visitBinaryExpr(*Binary) int16
	visitGroupingExpr(*Grouping) int16
	visitLiteralExpr(*Literal) int16
	visitUnaryExpr(*Unary) int16
}

type visitorInt32 interface {
	visitBinaryExpr(*Binary) int32
	visitGroupingExpr(*Grouping) int32
	visitLiteralExpr(*Literal) int32
	visitUnaryExpr(*Unary) int32
}

type visitorInt64 interface {
	visitBinaryExpr(*Binary) int64
	visitGroupingExpr(*Grouping) int64
	visitLiteralExpr(*Literal) int64
	visitUnaryExpr(*Unary) int64
}

type visitorUint interface {
	visitBinaryExpr(*Binary) uint
	visitGroupingExpr(*Grouping) uint
	visitLiteralExpr(*Literal) uint
	visitUnaryExpr(*Unary) uint
}

type visitorUint8 interface {
	visitBinaryExpr(*Binary) uint8
	visitGroupingExpr(*Grouping) uint8
	visitLiteralExpr(*Literal) uint8
	visitUnaryExpr(*Unary) uint8
}

type visitorUint16 interface {
	visitBinaryExpr(*Binary) uint16
	visitGroupingExpr(*Grouping) uint16
	visitLiteralExpr(*Literal) uint16
	visitUnaryExpr(*Unary) uint16
}

type visitorUint32 interface {
	visitBinaryExpr(*Binary) uint32
	visitGroupingExpr(*Grouping) uint32
	visitLiteralExpr(*Literal) uint32
	visitUnaryExpr(*Unary) uint32
}

type visitorUint64 interface {
	visitBinaryExpr(*Binary) uint64
	visitGroupingExpr(*Grouping) uint64
	visitLiteralExpr(*Literal) uint64
	visitUnaryExpr(*Unary) uint64
}

type visitorUintptr interface {
	visitBinaryExpr(*Binary) uintptr
	visitGroupingExpr(*Grouping) uintptr
	visitLiteralExpr(*Literal) uintptr
	visitUnaryExpr(*Unary) uintptr
}

type visitorByte interface {
	visitBinaryExpr(*Binary) byte
	visitGroupingExpr(*Grouping) byte
	visitLiteralExpr(*Literal) byte
	visitUnaryExpr(*Unary) byte
}

type visitorRune interface {
	visitBinaryExpr(*Binary) rune
	visitGroupingExpr(*Grouping) rune
	visitLiteralExpr(*Literal) rune
	visitUnaryExpr(*Unary) rune
}

type visitorFloat32 interface {
	visitBinaryExpr(*Binary) float32
	visitGroupingExpr(*Grouping) float32
	visitLiteralExpr(*Literal) float32
	visitUnaryExpr(*Unary) float32
}

type visitorFloat64 interface {
	visitBinaryExpr(*Binary) float64
	visitGroupingExpr(*Grouping) float64
	visitLiteralExpr(*Literal) float64
	visitUnaryExpr(*Unary) float64
}

type visitorComplex64 interface {
	visitBinaryExpr(*Binary) complex64
	visitGroupingExpr(*Grouping) complex64
	visitLiteralExpr(*Literal) complex64
	visitUnaryExpr(*Unary) complex64
}

type visitorComplex128 interface {
	visitBinaryExpr(*Binary) complex128
	visitGroupingExpr(*Grouping) complex128
	visitLiteralExpr(*Literal) complex128
	visitUnaryExpr(*Unary) complex128
}

type Binary struct {
	left     Expr
	operator Token
	right    Expr
}

// Binary implements Expr
var _ Expr = &Binary{}

func NewBinary(left Expr, operator Token, right Expr) *Binary {
	return &Binary{
		left:     left,
		operator: operator,
		right:    right,
	}
}

func (expr *Binary) Accept(v visitor) interface{} {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptBool(v visitorBool) bool {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptString(v visitorString) string {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptInt(v visitorInt) int {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptInt8(v visitorInt8) int8 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptInt16(v visitorInt16) int16 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptInt32(v visitorInt32) int32 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptInt64(v visitorInt64) int64 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptUint(v visitorUint) uint {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptUint8(v visitorUint8) uint8 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptUint16(v visitorUint16) uint16 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptUint32(v visitorUint32) uint32 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptUint64(v visitorUint64) uint64 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptUintptr(v visitorUintptr) uintptr {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptByte(v visitorByte) byte {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptRune(v visitorRune) rune {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptFloat32(v visitorFloat32) float32 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptFloat64(v visitorFloat64) float64 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptComplex64(v visitorComplex64) complex64 {
	return v.visitBinaryExpr(expr)
}

func (expr *Binary) AcceptComplex128(v visitorComplex128) complex128 {
	return v.visitBinaryExpr(expr)
}

type Grouping struct {
	expression Expr
}

// Grouping implements Expr
var _ Expr = &Grouping{}

func NewGrouping(expression Expr) *Grouping {
	return &Grouping{
		expression: expression,
	}
}

func (expr *Grouping) Accept(v visitor) interface{} {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptBool(v visitorBool) bool {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptString(v visitorString) string {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptInt(v visitorInt) int {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptInt8(v visitorInt8) int8 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptInt16(v visitorInt16) int16 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptInt32(v visitorInt32) int32 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptInt64(v visitorInt64) int64 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptUint(v visitorUint) uint {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptUint8(v visitorUint8) uint8 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptUint16(v visitorUint16) uint16 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptUint32(v visitorUint32) uint32 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptUint64(v visitorUint64) uint64 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptUintptr(v visitorUintptr) uintptr {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptByte(v visitorByte) byte {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptRune(v visitorRune) rune {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptFloat32(v visitorFloat32) float32 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptFloat64(v visitorFloat64) float64 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptComplex64(v visitorComplex64) complex64 {
	return v.visitGroupingExpr(expr)
}

func (expr *Grouping) AcceptComplex128(v visitorComplex128) complex128 {
	return v.visitGroupingExpr(expr)
}

type Literal struct {
	value interface{}
}

// Literal implements Expr
var _ Expr = &Literal{}

func NewLiteral(value interface{}) *Literal {
	return &Literal{
		value: value,
	}
}

func (expr *Literal) Accept(v visitor) interface{} {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptBool(v visitorBool) bool {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptString(v visitorString) string {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptInt(v visitorInt) int {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptInt8(v visitorInt8) int8 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptInt16(v visitorInt16) int16 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptInt32(v visitorInt32) int32 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptInt64(v visitorInt64) int64 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptUint(v visitorUint) uint {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptUint8(v visitorUint8) uint8 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptUint16(v visitorUint16) uint16 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptUint32(v visitorUint32) uint32 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptUint64(v visitorUint64) uint64 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptUintptr(v visitorUintptr) uintptr {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptByte(v visitorByte) byte {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptRune(v visitorRune) rune {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptFloat32(v visitorFloat32) float32 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptFloat64(v visitorFloat64) float64 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptComplex64(v visitorComplex64) complex64 {
	return v.visitLiteralExpr(expr)
}

func (expr *Literal) AcceptComplex128(v visitorComplex128) complex128 {
	return v.visitLiteralExpr(expr)
}

type Unary struct {
	operator Token
	right    Expr
}

// Unary implements Expr
var _ Expr = &Unary{}

func NewUnary(operator Token, right Expr) *Unary {
	return &Unary{
		operator: operator,
		right:    right,
	}
}

func (expr *Unary) Accept(v visitor) interface{} {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptBool(v visitorBool) bool {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptString(v visitorString) string {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptInt(v visitorInt) int {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptInt8(v visitorInt8) int8 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptInt16(v visitorInt16) int16 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptInt32(v visitorInt32) int32 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptInt64(v visitorInt64) int64 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptUint(v visitorUint) uint {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptUint8(v visitorUint8) uint8 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptUint16(v visitorUint16) uint16 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptUint32(v visitorUint32) uint32 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptUint64(v visitorUint64) uint64 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptUintptr(v visitorUintptr) uintptr {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptByte(v visitorByte) byte {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptRune(v visitorRune) rune {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptFloat32(v visitorFloat32) float32 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptFloat64(v visitorFloat64) float64 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptComplex64(v visitorComplex64) complex64 {
	return v.visitUnaryExpr(expr)
}

func (expr *Unary) AcceptComplex128(v visitorComplex128) complex128 {
	return v.visitUnaryExpr(expr)
}
